/**
 * TEMPLATE: Visual Regression Test for a Component
 *
 * Copy this file and rename to: [component-name].visual.spec.ts
 *
 * Example: button.visual.spec.ts, input.visual.spec.ts, modal.visual.spec.ts
 *
 * NOTE: This file is typically auto-generated by running:
 *   pnpm generate:visual-tests
 *
 * Only use this template if you need custom test logic that can't be
 * expressed in your VRT stories.
 */

import { expect, test } from "@playwright/test";

const getStorybookUrl = ({ storyId }: { storyId: string }) => {
	return `/iframe.html?id=${storyId}&viewMode=story`;
};

// Update the component name and story path
test.describe("ComponentName - Visual Regression", () => {
	test("Default state", async ({ page }) => {
		await page.goto(
			getStorybookUrl({
				// Update story ID format: components-{component-name}-tests-visual-regression-tests--{story-name}
				storyId:
					"components-componentname-tests-visual-regression-tests--default",
			}),
		);

		// Optional: Wait for specific element to be ready
		// await page.waitForSelector('[data-testid="component"]', {
		// 	state: "visible",
		// 	timeout: 5000,
		// });

		// Snapshot name should be descriptive: {component}-{variant}.png
		await expect(page).toHaveScreenshot("componentname-default.png");
	});

	test("With props variant", async ({ page }) => {
		await page.goto(
			getStorybookUrl({
				storyId:
					"components-componentname-tests-visual-regression-tests--with-props",
			}),
		);
		await expect(page).toHaveScreenshot("componentname-with-props.png");
	});

	// Add more tests for:
	// - Different states (hover, active, disabled)
	// - Different variants (sizes, colors, etc.)
	// - Edge cases (long text, empty state, etc.)
	// - Different viewports (mobile, tablet, desktop)
	// - Accessibility states (focus, error, etc.)
});
